version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfephp-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
    networks:
      - nfe-network

  webserver:
    image: nginx:alpine
    container_name: nfephp-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - nfe-network

networks:
  nfe-network:
    driver: bridge
